master-cronevent.testc: Avoid a fatalized format warning with gcc's ubsan
With the optimizer enabled, gcc -fsanitize=undefined issues a format warning.
This is fatal with -Werror, stopping the build dead:

    error: '%d' directive output may be truncated writing between 1 and 11 bytes into a region of size 10 [-Werror=format-truncation=]
    note: directive argument in the range [-2147483647, 2]

This inference is actually incorrect - the range is [0, 2] hence "%d" can't
overflow. The "obvious" fix is to increase the buffer length. A better fix
is to change the variable to unsigned int and the format to "%u", as it's
used as an array index. Using (default) signed variables for array indexes
is an anti-pattern that can cause CVE-level bugs.